### ISSUE TITLE
Publicar el CSV de datos en el landing

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/concesionopoly#1]
La comunidad OpenData lo pide!

![screen shot 2015-07-02 at 11 48 15 am](https://cloud.githubusercontent.com/assets/2538465/8479776/3e7c92fa-20b0-11e5-9730-ff43069d9d6b.png)

**Comment by martinvol** [comment]
viste que está en el about?

http://concesionopoly.com.ar/about/

**Comment by gvilarino** [comment]
Sí. Lo que te digo es que los usuarios no lo ven de entrada y presta a confusión.

**Comment by gvilarino** [comment]
Y estamos hablando de gente de la comunidad de open data; que saben buscar.

**Comment by piamancini** [comment]
si pero habria que hacerlo mas visible si se puede.

P.
piamancini.com
t: @piamancini
s: piamancini
democracyos.org
democraciaenred.org

**Comment by martinvol** [comment]
Please manden un PR que yo hoy no voy a poder tocar código :(

**Comment by mjlescano** [comment]
Hoy a la noche mando
