### ISSUE TITLE
Los links dentro del iframe renavegan sólo el iframe

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/concesionopoly#7]
falta `target="_parent"`

**Comment by martinvol** [comment]
Guarda con esto, porque si no modificás el .jade cuando se vuelva a compilar va a pisar esos cambios.
Es así @mjlescano?

**Comment by gvilarino** [comment]
En este caso no porque los `jade` que tenemos hacen include de los `html`s donde hice los cambios.

**Comment by martinvol** [comment]
Genial, no dije nada :)
